name: Food reminder

on:
  schedule:
    - cron: '0 8 * * 2-3'
  workflow_dispatch:

jobs:
  start-sending:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Send to TG
      run: |
        pip install requests
        python3 food.py
      env:
        TOKEN: ${{ secrets.TOKEN }}
